name: build
on:
  push: {} # TODO: fix before merge
  pull_request: {}
concurrency: ${{ github.ref }}
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: [gyg-gha-runner-16x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # TODO: use a GYG registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}    # TODO: use a GYG registry

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        pull: true
        file: tools/router-check-tool/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ startsWith(github.ref_name, 'release-') && github.event_name == 'push'}}
        tags: cainelli/router_check_tool:${{ github.ref_name }}
