name: build
on:
  push:
    {}
    # branches:
    #   - release-1.23

concurrency: ${{ github.ref }}
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: [gyg-gha-runner-32x128]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Envoy
        run: |
          BUILD_WITH_CONTAINER=1 make;
          find . -maxdepth 3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          pull: true
          file: Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: getyourguide/proxy:1.23.3-patch
